stages:
    - build
    - test
    - publish

variables:

.commonscript: &common_script
     tags: 
        -  docker
image:
  name: docker/compose:latest
  entrypoint: ["/bin/sh", "-c"]

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version



Build:build:
    stage: build
    script:
        - echo "------Build-Start----------"
        - docker-compose build
         # Log in to the docker CLI
        - echo "$DOCKER_HUB_ACCESS_KEY" | docker login -u "$DOCKER_ID" --password-stdin
         # Take those images and push them to docker hub
        - docker push sdontireddy/wordcloudgenerator:latest
        - echo "------Build-Done----------"
        
test:simple-tests:
    stage: test
    script:
        - |
            echo "-----------------------------Test-----------------------------"

publish:PublishTOAws:
    stage: publish
    <<: *common_script
    script:
        - |
            echo "-----------------------------Publish-----------------------------"