stages:
    - build
    - test
    - publish

variables:

.commonscript: &common_script
     image: ruby:2.6


Build:build:
    stage: build
    script:
        - echo "------Build-----------""
test:simple-tests:
    stage: test
    script:
        - |
            echo "-----------------------------Test-----------------------------"

publish:PublishTOAws:
    stage: publish
    <<: *common_script
    script:
        - |
            echo "-----------------------------Publish-----------------------------"
    

    