stages:
    - build
    - test
    - publish

variables:

.commonscript: &common_script
     tags: 
        -  docker
     image: qmarketing/docker-compose:latest


Build:build:
    stage: build
    script:
        - echo "------Build-----------"
        - docker -version
        - docker-compose -version
test:simple-tests:
    stage: test
    script:
        - |
            echo "-----------------------------Test-----------------------------"

publish:PublishTOAws:
    stage: publish
    <<: *common_script
    script:
        - |
            echo "-----------------------------Publish-----------------------------"
