version: '3.4'

services:
  wordcloudgenerator:
    image: sdontireddy/wordcloudgenerator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: "true"
